platform :ios, '7.0'
pod "AFNetworking"
pod 'MKNetworkKit'
pod 'SDWebImage', '~> 3.7.1'
pod 'SVProgressHUD', '~> 1.0'
pod 'MJExtension', '~> 0.2.0'
pod 'MJRefresh'
pod 'Masonry'
pod 'AlipaySDK-2.0', '~> 2.0.3'
pod 'Nimbus'
pod 'RZCellSizeManager'
